import IsAuthAlive from "@/components/isAuthAlive/isAuthAlive";
import Sidebar from "@/components/sidebar/sidebar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    // useEffect
  return (
        <IsAuthAlive>
            <Sidebar />
            {children}
        </IsAuthAlive>
      
  );
}
